repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  # - repo: https://github.com/python-poetry/poetry
  #   rev: '1.5.1'
  #   hooks:
  #     - id: poetry-check
  #       name: poetry check
  #       args: ["-C", "miniduct"]
  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry -C run black .
        language: system
        types: [file, python]
        files: '^(src|tests)/'
      - id: ruff
        name: ruff
        entry: poetry -C run ruff check --fix
        language: system
        types: [file, python]
        files: '^(src|tests)/'
      - id: test
        name: pytest
        entry: poetry -C run pytest
        language: system
        types: [file, python]
        files: '^(src|tests)/'
