name: Package Release

on: workflow_dispatch

permissions:
  contents: read

jobs:
  test:
    uses: ./.github/workflows/package-check.yml
    with:
      python-version: '3.12'
      poetry-version: '1.5.1'
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build package
      working-directory: miniduct
      run: |
        poetry build
    - name: Publish package
      working-directory: miniduct
      run: |
        poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
        poetry publish --build --username __token__ --password ${{ secrets.PYPI_TOKEN }}
      env:
        POETRY_HTTP_BASIC_PYPI_USERNAME: __token__
        POETRY_HTTP_BASIC_PYPI_PASSWORD: ${{ secrets.PYPI_TOKEN }}
    - name: Clean up
      run: |
        rm -rf .venv
        rm -rf dist
        rm -rf .pytest_cache
        rm -rf .ruff_cache
        rm -rf .mypy_cache
