name: Poetry Release

on:
  workflow_dispatch:
  release:
    types: [created]
permissions:
  contents: read

jobs:
  release-build:
    runs-on: ubuntu-latest
    steps:
      - name: Publish python poetry package
        uses: JRubics/poetry-publish@v2.1
        with:
          python_version: "3.12"
          pypi_token: ${{ secrets.PYPI_TOKEN }}
