name: Poetry Release

on:
  workflow_dispatch:
  release:
    types: [created]
permissions:
  contents: read

jobs:
  release-build:
    runs-on: ubuntu-latest
    steps:
      - name: Publish python poetry package
        uses: JRubics/poetry-publish@v2.1
        with:
          python-version: "3.12"
          poetry-version: "1.8.0"
          package-directory: miniduct
          pypi-token: ${{ secrets.PYPI_TOKEN }}
          poetry-install-options: "-C miniduct"
          skip-checks: true
